export const OPERARIOS = [
  { id:1, nombre:'James Rodriguez',  cargo:'Prensista',   pin:'2501', iniciales:'JR', activo:true },
  { id:2, nombre:'Andres Moreno',    cargo:'Troquelador', pin:'2502', iniciales:'AM', activo:true },
  { id:3, nombre:'Juliana Cortes',   cargo:'Papeleras',   pin:'2503', iniciales:'JC', activo:true },
  { id:4, nombre:'Teresa Sierra',    cargo:'Papeleras',   pin:'2504', iniciales:'TS', activo:true },
  { id:5, nombre:'Alejandro Rodriguez', cargo:'Mensajero',pin:'2505', iniciales:'AL', activo:true },
  { id:6, nombre:'Maria Montoya',    cargo:'Papeleras',   pin:'2506', iniciales:'MM', activo:false },
  { id:7, nombre:'Luz Elena Carvajal',cargo:'Papeleras',  pin:'2507', iniciales:'LE', activo:false },
  { id:8, nombre:'Paola Salazar',    cargo:'Papeleras',   pin:'2508', iniciales:'PS', activo:false },
  { id:9, nombre:'Juan Carlos Quintero',cargo:'Operario', pin:'2509', iniciales:'JQ', activo:true },
  { id:10,nombre:'Juan Manuel Quintero',cargo:'Operario', pin:'2510', iniciales:'JM', activo:true },
  { id:11,nombre:'Liliana Giraldo',  cargo:'Operario',    pin:'2511', iniciales:'LG', activo:true },
  { id:12,nombre:'Julian Quintero',  cargo:'Operario',    pin:'2512', iniciales:'JU', activo:true },
]

export const MAQUINAS = [
  { cod:'P1', nombre:'GTO 525',          area:'Litografía' },
  { cod:'P2', nombre:'Adast Dominant 2', area:'Litografía' },
  { cod:'G1', nombre:'Guillotina',       area:'Guillotina' },
  { cod:'Tr', nombre:'Troqueladora',     area:'Troquelado' },
  { cod:'L1', nombre:'Laminadora',       area:'Plastificado' },
  { cod:'L2', nombre:'Laminadora Manual',area:'Plastificado' },
  { cod:'D1', nombre:'Xerox 700',        area:'Impresión Digital' },
  { cod:'Ar', nombre:'Argolladora',      area:'Terminado' },
  { cod:'C1', nombre:'Cosedora Manual 1',area:'Terminado' },
  { cod:'C2', nombre:'Cosedora Manual 2',area:'Terminado' },
  { cod:'C3', nombre:'Cosedora Manual 3',area:'Terminado' },
  { cod:'En', nombre:'Engomadora',       area:'Terminado' },
  { cod:'Pe', nombre:'Perforadora',      area:'Terminado' },
  { cod:'T',  nombre:'Taladro',          area:'Terminado' },
]

export const ACTIVIDADES = [
  { cod:'1201', label:'Calibración',            area:'Litografía',        tipo:'directa' },
  { cod:'1202', label:'Arreglo Inicial',         area:'Litografía',        tipo:'directa' },
  { cod:'1203', label:'Impresión',               area:'Litografía',        tipo:'directa' },
  { cod:'1204', label:'Preparar Tintas',         area:'Litografía',        tipo:'directa' },
  { cod:'1205', label:'Esperar Secado',          area:'Litografía',        tipo:'directa' },
  { cod:'1301', label:'Preparar Maquina',        area:'Guillotina',        tipo:'directa' },
  { cod:'1302', label:'Cortar Papel Inicial',    area:'Guillotina',        tipo:'directa' },
  { cod:'1303', label:'Corte Final',             area:'Guillotina',        tipo:'directa' },
  { cod:'1401', label:'Preparar Maquina',        area:'Troquelado',        tipo:'directa' },
  { cod:'1402', label:'Encauchetar',             area:'Troquelado',        tipo:'directa' },
  { cod:'1403', label:'Troquelar',               area:'Troquelado',        tipo:'directa' },
  { cod:'1404', label:'Estriar',                 area:'Troquelado',        tipo:'directa' },
  { cod:'1405', label:'Pretroquelado',           area:'Troquelado',        tipo:'directa' },
  { cod:'1406', label:'Repujar',                 area:'Troquelado',        tipo:'directa' },
  { cod:'1407', label:'Perforar',                area:'Troquelado',        tipo:'directa' },
  { cod:'1408', label:'Hot Stamping',            area:'Troquelado',        tipo:'directa' },
  { cod:'1501', label:'Preparar Maquina',        area:'Plastificado',      tipo:'directa' },
  { cod:'1503', label:'Plastificar',             area:'Plastificado',      tipo:'directa' },
  { cod:'1601', label:'Preparar Maquina',        area:'Engomadora',        tipo:'directa' },
  { cod:'1602', label:'Engomar',                 area:'Engomadora',        tipo:'directa' },
  { cod:'1603', label:'Engomar y poner Caratula',area:'Engomadora',        tipo:'directa' },
  { cod:'1604', label:'Engomar y poner Guarda',  area:'Engomadora',        tipo:'directa' },
  { cod:'1605', label:'Cerrado de pestañas',     area:'Engomadora',        tipo:'directa' },
  { cod:'1701', label:'Recoger Producción',      area:'Terminado',         tipo:'directa' },
  { cod:'1702', label:'Revisar y Contar',        area:'Terminado',         tipo:'directa' },
  { cod:'1703', label:'Limpiar',                 area:'Terminado',         tipo:'directa' },
  { cod:'1704', label:'Plegar',                  area:'Terminado',         tipo:'directa' },
  { cod:'1705', label:'Levantar',                area:'Terminado',         tipo:'directa' },
  { cod:'1706', label:'Emblocar',                area:'Terminado',         tipo:'directa' },
  { cod:'1707', label:'Enganchar',               area:'Terminado',         tipo:'directa' },
  { cod:'1708', label:'Despuntar',               area:'Terminado',         tipo:'directa' },
  { cod:'1709', label:'Descolillar',             area:'Terminado',         tipo:'directa' },
  { cod:'1710', label:'Perforar Taladro',        area:'Terminado',         tipo:'directa' },
  { cod:'1711', label:'Separar Tacos',           area:'Terminado',         tipo:'directa' },
  { cod:'1712', label:'Perforar Tacos',          area:'Terminado',         tipo:'directa' },
  { cod:'1713', label:'Cortar Argolla',          area:'Terminado',         tipo:'directa' },
  { cod:'1714', label:'Argollar',                area:'Terminado',         tipo:'directa' },
  { cod:'1716', label:'Encolbonar',              area:'Terminado',         tipo:'directa' },
  { cod:'1717', label:'Encintar',                area:'Terminado',         tipo:'directa' },
  { cod:'1718', label:'Doblar y pegar',          area:'Terminado',         tipo:'directa' },
  { cod:'1721', label:'Contar y Reportar',       area:'Terminado',         tipo:'directa' },
  { cod:'1722', label:'Empacar y Rotular',       area:'Terminado',         tipo:'directa' },
  { cod:'2101', label:'Archivo de Planchas',     area:'General',           tipo:'indirecta' },
  { cod:'2102', label:'Ayudar a Mantenimiento',  area:'General',           tipo:'indirecta' },
  { cod:'2103', label:'Capacitación',            area:'General',           tipo:'indirecta' },
  { cod:'2104', label:'Descargar Materia Prima', area:'General',           tipo:'indirecta' },
  { cod:'2105', label:'Hacer Aseo',              area:'General',           tipo:'indirecta' },
  { cod:'2106', label:'Hacer Inventarios',       area:'General',           tipo:'indirecta' },
  { cod:'2107', label:'Mantenimiento Preventivo',area:'General',           tipo:'indirecta' },
  { cod:'2108', label:'Lubricación y Limpieza',  area:'General',           tipo:'indirecta' },
  { cod:'2109', label:'Cambiar Cuchilla',        area:'Guillotina',        tipo:'indirecta' },
  { cod:'2110', label:'Cortar Macula',           area:'Guillotina',        tipo:'indirecta' },
  { cod:'2111', label:'Hacer Muestrarios',       area:'Terminado',         tipo:'indirecta' },
  { cod:'3101', label:'Esperando Aprobación',    area:'General',           tipo:'paro' },
  { cod:'3102', label:'Esperando Asignación',    area:'General',           tipo:'paro' },
  { cod:'3103', label:'Esperando Papel',         area:'General',           tipo:'paro' },
  { cod:'3104', label:'Esperando Producción',    area:'General',           tipo:'paro' },
  { cod:'3105', label:'Esperando Suministros',   area:'General',           tipo:'paro' },
  { cod:'4101', label:'Descanso Desayuno',       area:'General',           tipo:'legales' },
  { cod:'4102', label:'Descanso Almuerzo',       area:'General',           tipo:'legales' },
  { cod:'4103', label:'Descanso Comida',         area:'General',           tipo:'legales' },
  { cod:'4104', label:'Incapacidad',             area:'General',           tipo:'legales' },
  { cod:'4105', label:'Permiso Remunerado',      area:'General',           tipo:'legales' },
  { cod:'4106', label:'Permiso No Remunerado',   area:'General',           tipo:'legales' },
]

export const PAPELES = [
  { cod:'B-70-1',         nombre:'Bond 70 gr 70x100' },
  { cod:'B-70-2',         nombre:'Bond 70 gr 60x90' },
  { cod:'B-90-1',         nombre:'Bond 90 gr 70x100' },
  { cod:'B-115-1',        nombre:'Bond 115 gr 70x100' },
  { cod:'Cote-115-C2-1',  nombre:'Propalcote 115 gr C2S 70x100' },
  { cod:'Cote-150-C2-1',  nombre:'Propalcote 150 gr C2S 70x100' },
  { cod:'Cote-200-C2-1',  nombre:'Propalcote 200 gr C2S 70x100' },
  { cod:'Cote-240-C2-1',  nombre:'Propalcote 240 gr C2S 70x100' },
  { cod:'Cote-300-C1-1',  nombre:'Propalcote 300 gr C1S 70x100' },
  { cod:'Cote-300-C2-1',  nombre:'Propalcote 300 gr C2S 70x100' },
  { cod:'Ca-Ma-30-RB-1',  nombre:'Cartulina Maule 0.30 R/Blanco 70x100' },
  { cod:'Ca-Ma-36-RB-1',  nombre:'Cartulina Maule 0.36 R/Blanco 70x100' },
  { cod:'Ca-Ma-40-RB-1',  nombre:'Cartulina Maule 0.40 R/Blanco 70x100' },
  { cod:'Ca-Ma-48-RB-1',  nombre:'Cartulina Maule 0.48 R/Blanco 70x100' },
  { cod:'Ca-280-RB-1',    nombre:'Cartulina 280 Reverso Blanco 70x100' },
  { cod:'Mate-150-1',     nombre:'Propalmate 150 gr 70x100' },
  { cod:'Mate-200-1',     nombre:'Propalmate 200 gr 70x100' },
  { cod:'Mate-240-1',     nombre:'Propalmate 240 gr 70x100' },
  { cod:'R-150-1',        nombre:'Reciclado Earth Pact 150 gr 70x100' },
  { cod:'R-200-1',        nombre:'Reciclado Earth Pact 200 gr 70x100' },
  { cod:'C-I-1',          nombre:'Carton Industrial 1.0 mm 70x100' },
  { cod:'C-I-2',          nombre:'Carton Industrial 1.25 mm 70x100' },
  { cod:'C-I-3',          nombre:'Carton Industrial 1.5 mm 70x100' },
]

export const TIPO_COLORS = {
  directa:   { dot:'#1D9E75', badge:'#E1F5EE', text:'#085041' },
  indirecta: { dot:'#185FA5', badge:'#E6F1FB', text:'#185FA5' },
  paro:      { dot:'#BA7517', badge:'#FAEEDA', text:'#BA7517' },
  legales:   { dot:'#888780', badge:'#F1EFE8', text:'#5F5E5A' },
}
